# [LogInUser]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [LogInUser]    Script Date: 23/6/2025 14:43:34 ******/
CREATE DATABASE [LogInUser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LogInUser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLSERVERMS2022\MSSQL\DATA\LogInUser.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LogInUser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLSERVERMS2022\MSSQL\DATA\LogInUser_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [LogInUser] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LogInUser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LogInUser] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LogInUser] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LogInUser] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LogInUser] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LogInUser] SET ARITHABORT OFF 
GO
ALTER DATABASE [LogInUser] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LogInUser] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LogInUser] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LogInUser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LogInUser] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LogInUser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LogInUser] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LogInUser] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LogInUser] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LogInUser] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LogInUser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LogInUser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LogInUser] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LogInUser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LogInUser] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LogInUser] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LogInUser] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LogInUser] SET RECOVERY FULL 
GO
ALTER DATABASE [LogInUser] SET  MULTI_USER 
GO
ALTER DATABASE [LogInUser] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LogInUser] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LogInUser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LogInUser] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LogInUser] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LogInUser] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'LogInUser', N'ON'
GO
ALTER DATABASE [LogInUser] SET QUERY_STORE = ON
GO
ALTER DATABASE [LogInUser] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Animal]

In [0]:
USE [LogInUser]
GO

In [0]:
/****** Object:  Table [dbo].[Animal]    Script Date: 23/6/2025 14:43:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Animal](
	[idAnimal] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NULL,
	[idEspecie] [int] NULL,
	[idTamaño] [int] NULL,
	[imagen] [varbinary](50) NOT NULL,
	[idRaza] [int] NULL,
	[edad] [int] NOT NULL,
	[idEstado] [int] NULL,
	[fechaIngreso] [datetime] NULL,
 CONSTRAINT [PK_Animal] PRIMARY KEY CLUSTERED 
(
	[idAnimal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Especie]

In [0]:
/****** Object:  Table [dbo].[Especie]    Script Date: 23/6/2025 14:43:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Especie](
	[idEspecie] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](50) NULL,
 CONSTRAINT [PK_Especie] PRIMARY KEY CLUSTERED 
(
	[idEspecie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Estado]

In [0]:
/****** Object:  Table [dbo].[Estado]    Script Date: 23/6/2025 14:43:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estado](
	[idEstado] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](50) NULL,
 CONSTRAINT [PK_Estado] PRIMARY KEY CLUSTERED 
(
	[idEstado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Raza]

In [0]:
/****** Object:  Table [dbo].[Raza]    Script Date: 23/6/2025 14:43:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Raza](
	[idRaza] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](50) NULL,
 CONSTRAINT [PK_Raza] PRIMARY KEY CLUSTERED 
(
	[idRaza] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Tamaño]

In [0]:
/****** Object:  Table [dbo].[Tamaño]    Script Date: 23/6/2025 14:43:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tamaño](
	[idTamaño] [int] IDENTITY(1,1) NOT NULL,
	[descripcion] [varchar](50) NULL,
 CONSTRAINT [PK_Tamaño] PRIMARY KEY CLUSTERED 
(
	[idTamaño] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[userTable]

In [0]:
/****** Object:  Table [dbo].[userTable]    Script Date: 23/6/2025 14:43:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[userTable](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[username] [nvarchar](50) NULL,
	[password] [nvarchar](50) NULL,
	[email] [nvarchar](100) NULL,
	[name] [nvarchar](50) NULL,
	[lastname] [nvarchar](50) NULL,
	[birthday] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [FK_Animal_Especie]

In [0]:
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_Especie] FOREIGN KEY([idEspecie])
REFERENCES [dbo].[Especie] ([idEspecie])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_Especie]
GO

# [FK_Animal_Estado]

In [0]:
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_Estado] FOREIGN KEY([idEstado])
REFERENCES [dbo].[Estado] ([idEstado])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_Estado]
GO

# [FK_Animal_Raza]

In [0]:
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_Raza] FOREIGN KEY([idRaza])
REFERENCES [dbo].[Raza] ([idRaza])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_Raza]
GO

# [FK_Animal_Tamaño]

In [0]:
ALTER TABLE [dbo].[Animal]  WITH CHECK ADD  CONSTRAINT [FK_Animal_Tamaño] FOREIGN KEY([idTamaño])
REFERENCES [dbo].[Tamaño] ([idTamaño])
GO
ALTER TABLE [dbo].[Animal] CHECK CONSTRAINT [FK_Animal_Tamaño]
GO

# [LogInUser]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [LogInUser] SET  READ_WRITE 
GO